### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by petk** [progit/progit2-sl#10]
Translate and sync the following:

- ├── 01-introduction
- [x]    │       ├── about-version-control.asc
- [x]    │       ├── command-line.asc
- [x]    │       ├── first-time-setup.asc
- [x]    │       ├── help.asc
- [x]    │       ├── history.asc
- [x]    │       ├── installing.asc
- [x]    │       └── what-is-git.asc
- ├── 02-git-basics
- [x]    │       ├── aliases.asc
- [x]    │       ├── getting-a-repository.asc
- [x]    │       ├── recording-changes.asc
- [x]    │       ├── remotes.asc
- [x]    │       ├── tagging.asc
- [x]    │       ├── undoing.asc
- [x]    │       └── viewing-history.asc
- ├── 03-git-branching
- [x]    │       ├── basic-branching-and-merging.asc
- [x]    │       ├── branch-management.asc
- [x]    │       ├── nutshell.asc
- [x]    │       ├── rebasing.asc
- [x]    │       ├── remote-branches.asc
- [x]    │       └── workflows.asc
- ├── 04-git-server
- [x]    │       ├── generating-ssh-key.asc
- [x]    │       ├── git-daemon.asc
- [x]    │       ├── gitlab.asc
- [x]    │       ├── git-on-a-server.asc
- [x]    │       ├── gitweb.asc
- [x]    │       ├── hosted.asc
- [x]    │       ├── protocols.asc
- [x]    │       ├── setting-up-server.asc
- [x]    │       └── smart-http.asc
- ├── 05-distributed-git
- [x]    │       ├── contributing.asc
- [x]    │       ├── distributed-workflows.asc
- [x]    │       └── maintaining.asc
- ├── 06-github
- [x]    │       ├── 1-setting-up-account.asc
- [x]    │       ├── 2-contributing.asc
- [x]    │       ├── 3-maintaining.asc
- [x]    │       ├── 4-managing-organization.asc
- [x]    │       └── 5-scripting.asc
- ├── 07-git-tools
- [x]    │       ├── advanced-merging.asc
- [x]    │       ├── bundling.asc
- [x]    │       ├── credentials.asc
- [x]    │       ├── debugging.asc
- [x]    │       ├── interactive-staging.asc
- [x]    │       ├── replace.asc
- [x]    │       ├── rerere.asc
- [x]    │       ├── reset.asc
- [x]    │       ├── revision-selection.asc
- [x]    │       ├── rewriting-history.asc
- [x]    │       ├── searching.asc
- [x]    │       ├── signing.asc
- [x]    │       ├── stashing-cleaning.asc
- [x]    │       ├── submodules.asc
- [x]    │       └── subtree-merges.asc
- ├── 08-customizing-git
- [x]    │       ├── attributes.asc
- [x]    │       ├── config.asc
- [x]    │       ├── hooks.asc
- [x]    │       └── policy.asc
- ├── 09-git-and-other-scms
- [x]    │       ├── client-bzr.asc
- [x]    │       ├── client-hg.asc
- [x]    │       ├── client-p4.asc
- [x]    │       ├── client-svn.asc
- [x]    │       ├── import-bzr.asc
- [x]    │       ├── import-custom.asc
- [x]    │       ├── import-hg.asc
- [x]    │       ├── import-p4.asc
- [x]    │       └── import-svn.asc
- ├── 10-git-internals
- [x]    │       ├── environment.asc
- [x]    │       ├── maintenance.asc
- [x]    │       ├── objects.asc
- [x]    │       ├── packfiles.asc
- [x]    │       ├── plumbing-porcelain.asc
- [x]    │       ├── refs.asc
- [x]    │       ├── refspec.asc
- [x]    │       └── transfer-protocols.asc
- ├── A-git-in-other-environments
- [x]    │       ├── bash.asc
- [x]    │       ├── guis.asc
- [x]    │       ├── jetbrainsides.asc
- [x]    │       ├── powershell.asc
- [x]    │       ├── sublimetext.asc
- [x]    │       ├── visualstudio.asc
- [x]    │       ├── visualstudiocode.asc
- [x]    │       └── zsh.asc
- ├── B-embedding-git
- [x]    │       ├── command-line.asc
- [x]    │       ├── dulwich.asc
- [x]    │       ├── go-git.asc
- [x]    │       ├── jgit.asc
- [x]    │       └── libgit2.asc
- [x]    ├── contributors.asc
- [x]    ├── dedication.asc
- [x]    ├── introduction.asc
- [x]    ├── license.asc
- [x]    ├── preface_ben.asc
- [x]    ├── preface_schacon.asc
- [x]    └── toc.asc
- [x]    A-git-in-other-environments.asc
- [x]    B-embedding-git-in-your-applications.asc
- [x]    C-git-commands.asc
- [x]    ch01-getting-started.asc
- [x]    ch02-git-basics-chapter.asc
- [x]    ch03-git-branching.asc
- [x]    ch04-git-on-the-server.asc
- [x]    ch05-distributed-git.asc
- [x]    ch06-github.asc
- [x]    ch07-git-tools.asc
- [x]    ch08-customizing-git.asc
- [x]    ch09-git-and-other-systems.asc
- [x]    ch10-git-internals.asc
- [x]    index.asc
- [x]    LICENSE.asc
- [x]    progit.asc

**Comment by petk** [comment]
Resolved via 1475da97a26c7bf4cfaf24742b33f77dd5b659e2
